import { Inter } from 'next/font/google'
import '../globals.css'
import Link from 'next/link'
import { AdminSidebarComponent, StudentSidebarComponent } from '../../components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const role = 'student'
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex h-screen'>
          <div className='w-[14%] p-4 border-r-2 border-black md:w-[8%] lg:w-[16%] xl:w-[14%]'>
            <Link
              href='/'
              className='flex items-center justify-center gap-2 lg:justify-start'
            >
              LO
              <span className='hidden font-bold lg:block'>CampusPro</span>
            </Link>
            {role == 'student' ? (
              <StudentSidebarComponent />
            ) : (
              <AdminSidebarComponent />
            )}
          </div>
          <div className='flex w-[86%] flex-col'>{children}</div>
        </div>
      </body>
    </html>
  )
}
